/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.dev/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganizationWithLogoAllOf {
    #[serde(rename = "logo_url")]
    pub logo_url: String,
}

impl OrganizationWithLogoAllOf {
    pub fn new(logo_url: String) -> OrganizationWithLogoAllOf {
        OrganizationWithLogoAllOf {
            logo_url,
        }
    }
}


