/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.dev/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateEmailAddressRequest {
    /// The email address will be marked as verified.
    #[serde(rename = "verified", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verified: Option<Option<bool>>,
    /// Set this email address as the primary email address for the user.
    #[serde(rename = "primary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary: Option<Option<bool>>,
}

impl UpdateEmailAddressRequest {
    pub fn new() -> UpdateEmailAddressRequest {
        UpdateEmailAddressRequest {
            verified: None,
            primary: None,
        }
    }
}


